version: "3.9"

services:
  mongo:
    image: mongo:7.0-jammy
    container_name: penart-mongo
    command: ["--bind_ip_all", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u $$MONGO_ROOT_USER -p $$MONGO_ROOT_PASS --eval 'db.adminCommand(\"ping\").ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: penart-app
    env_file:
      - .env
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      BASE_URL: ${BASE_URL:-http://localhost:8000}
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/${MONGO_DB:-penart}?authSource=admin
      TIMEZONE: ${TIMEZONE:-Asia/Seoul}
      DEFAULT_LANG: ${DEFAULT_LANG:-ko}
      ORDER_EXPIRE_HOURS: ${ORDER_EXPIRE_HOURS:-48}
      INVENTORY_POLICY: ${INVENTORY_POLICY:-hold}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: penart-mongo-express
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS:-change-me}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongo-data: